### ISSUE TITLE
wow error: Unknown unicode error

### ISSUE THREAD

**Issue by M4rtinK** [thiderman/doge#59]
such traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/doge/core.py", line 465, in main
    shibe.setup()
  File "/usr/lib/python3.4/site-packages/doge/core.py", line 40, in setup
    doge = self.load_doge()
  File "/usr/lib/python3.4/site-packages/doge/core.py", line 153, in load_doge
    doge_lines = [l for l in f.readlines()]
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 29: ordinal not in range(128)

```

wow /usr/bin/locale:

```
[nemo@Jolla software]$ /usr/bin/locale
/usr/bin/locale: Cannot set LC_CTYPE to default locale: No such file or directory
/usr/bin/locale: Cannot set LC_MESSAGES to default locale: No such file or directory
/usr/bin/locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=cs_CZ.UTF-8
LANGUAGE=
LC_CTYPE="cs_CZ.UTF-8"
LC_NUMERIC="cs_CZ.UTF-8"
LC_TIME="cs_CZ.UTF-8"
LC_COLLATE="cs_CZ.UTF-8"
LC_MONETARY="cs_CZ.UTF-8"
LC_MESSAGES="cs_CZ.UTF-8"
LC_PAPER="cs_CZ.UTF-8"
LC_NAME="cs_CZ.UTF-8"
LC_ADDRESS="cs_CZ.UTF-8"
LC_TELEPHONE="cs_CZ.UTF-8"
LC_MEASUREMENT="cs_CZ.UTF-8"
LC_IDENTIFICATION="cs_CZ.UTF-8"
LC_ALL=
``
```

**Comment by M4rtinK** [comment]
BTW, this happened when I tried running doge 3.5 on my Jolla with Sailfish OS from a self-made package[0] based on the Fedora spec file.

[0] https://build.merproject.org/package/show/home:MartinK:sailfish/doge

**Comment by g-cole** [comment]
I was just searching for the unicode decode error for an unrelated server install, but I thought I would mention that I have doge running on the latest Jolla Sailfish OS (3.0.3.10 - Xperia X). Works great with FingerTerm & ToeTerm (landscape or small doge error + Python 3.7.2). This ancient bug could probably be closed.
